apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-todo
  name: my-todo-service
spec:
  type: ClusterIP
  selector:
    app: my-todo
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
