apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-todo-list
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sokube/simple-todo-list.git
    targetRevision: dev
    path: argocd/app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-todo
  syncPolicy:
    automated:
      prune: false
      selfHeal: false