apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-todo
  template:
    metadata:
      labels:
        app: simple-todo
    spec:
      containers:
      - name: my-simple-todolist
        image: harbor.fabrice.local/dev/simple-todo-list:3.1.4
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 5
          initialDelaySeconds: 5
          timeoutSeconds: 1