apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-deployment
  labels:
    app: my-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-todo
  template:
    metadata:
      labels:
        app: my-todo
    spec:
      containers:
      - name: my-todo-container
        image: harbor.fabrice.local/test/simple-todo-list:3.1.8
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 5
          initialDelaySeconds: 5
          timeoutSeconds: 1
      imagePullSecrets:
      - name: regcred